services:
  judge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nice-judge
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - NODE_ENV=development
